src/main/java/com/example/controller/admin/AdminController.java
src/main/webapp/WEB-INF/views/admin/adminAddFacilities.jsp
src/main/webapp/WEB-INF/views/admin/adminBlacklist.jsp
src/main/webapp/WEB-INF/views/admin/adminCafe.jsp
src/main/webapp/WEB-INF/views/admin/adminDog.jsp
src/main/webapp/WEB-INF/views/admin/adminFuneralhall.jsp
src/main/webapp/WEB-INF/views/admin/adminHospital.jsp
src/main/webapp/WEB-INF/views/admin/adminHotel.jsp
src/main/webapp/WEB-INF/views/admin/adminLogin.jsp
src/main/webapp/WEB-INF/views/admin/adminMember.jsp
src/main/webapp/WEB-INF/views/admin/adminShelter.jsp
src/main/webapp/WEB-INF/views/admin/adminSidebar.jsp
src/main/webapp/WEB-INF/views/index.jsp

[kosmoFinal05에서 kosmoFinal5로 프로젝트 이동]
- index페이지에 admin링크 </br>로 간격만 수정
- view-admin폴더 지금까지 만든 페이지 다시 추가 함

관리자 페이지 수정ver3

---

src/main/java/com/example/controller/WalkController.java
src/main/webapp/WEB-INF/views/include/Main.jsp

메인페이지 디자인 수정

---

src/main/java/com/example/controller/CommunityController.java
src/main/java/com/example/controller/FriendController.java
src/main/webapp/WEB-INF/views/include/community/dailyDetail.jsp
src/main/webapp/WEB-INF/views/include/community/writeDaily.jsp
src/main/webapp/WEB-INF/views/include/friends/friend.jsp
src/main/webapp/WEB-INF/views/index.jsp

커뮤니티 게시글 작성 페이지

---

src/main/java/com/example/domain/FriendVO.java
src/main/java/com/example/domain/ReviewVO.java

vo 클래스 수정2

---

src/main/java/com/example/controller/ChattingController/ChatingController.java
src/main/java/com/example/dao/AgencyRepository.java
src/main/java/com/example/dao/ChatingRoomRepository.java
src/main/java/com/example/dao/CommentVORepository.java
src/main/java/com/example/domain/AgencyVO.java
src/main/java/com/example/domain/CommentVO.java
src/main/java/com/example/domain/CommunityVO.java
src/main/java/com/example/domain/FriendChatingVO.java
src/main/java/com/example/domain/FriendVO.java
src/main/java/com/example/domain/ImgVO.java
src/main/java/com/example/domain/LikeItVO.java
src/main/java/com/example/domain/PetVO.java
src/main/java/com/example/domain/ReportVO.java
src/main/java/com/example/domain/ReviewVO.java

vo class 수정 미안   (int --> Integer)

---

src/main/java/com/example/dao/CommentRepository.java
src/main/java/com/example/dao/CommunityRepository.java
src/main/java/com/example/dao/DogKindRepository.java
src/main/java/com/example/dao/FriendChatingRepository.java
src/main/java/com/example/dao/FriendRepository.java
src/main/java/com/example/dao/ImgRepository.java
src/main/java/com/example/dao/LikeItRepository.java
src/main/java/com/example/dao/PetRepository.java
src/main/java/com/example/dao/ReportRepository.java
src/main/java/com/example/dao/ReviewRepository.java
src/main/java/com/example/dao/UserRepository.java

테이블 repository 생성

---

src/main/java/com/example/controller/ChattingController/ChatingController.java
src/main/java/com/example/dao/DogKindRepository.java
src/main/java/com/example/dao/FriendChatingRepository.java
src/main/java/com/example/dao/FriendRepository.java
src/main/java/com/example/dao/ImgRepository.java
src/main/java/com/example/dao/LikeItRepository.java
src/main/java/com/example/dao/PetRepository.java
src/main/java/com/example/dao/ReportRepository.java
src/main/java/com/example/dao/ReviewRepository.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/handler/SocketHandler.java
src/main/resources/static/css/chating/chatingFriend.css
src/main/webapp/WEB-INF/views/chating/chat.jsp

repository 수정    채팅방 화면 바꾸기

---

src/main/resources/static/css/HeadFootPage.css
src/main/webapp/WEB-INF/views/include/Header.jsp
src/main/webapp/WEB-INF/views/include/Main.jsp

헤더 디자인 수정중

---

src/main/webapp/WEB-INF/views/include/community/writeDaily.jsp
src/main/webapp/WEB-INF/views/include/friend/friendFind.jsp
src/main/webapp/WEB-INF/views/include/friend/friendList.jsp
src/main/webapp/WEB-INF/views/include/friend/friendProfile.jsp

커뮤니티&친구 페이지 수정 중

---

src/main/java/com/example/controller/HomeController.java
src/main/resources/static/myPage/css/myPage.css
src/main/webapp/WEB-INF/views/include/myPage/myPageProfile.jsp
src/main/webapp/WEB-INF/views/index.jsp

myPage_profile add

---

src/main/resources/static/css/HeadFootPage.css
src/main/resources/static/css/lana-pet-theme.css
src/main/webapp/WEB-INF/views/include/Header.jsp

header fix

---

src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/domain/DogKindVO.java
src/main/java/com/example/domain/ImgVO.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/webapp/WEB-INF/views/chating/room.jsp

수헌씨 service 구현

---

src/main/resources/static/css/HeadFootPage.css
src/main/webapp/WEB-INF/views/include/Header.jsp
src/main/webapp/WEB-INF/views/include/Login.jsp

header under repairs

---

src/main/java/com/example/controller/ChattingController/ChatingController.java
src/main/java/com/example/dao/ChatingRoomRepository.java
src/main/java/com/example/domain/ChatingRoomVO.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/webapp/WEB-INF/views/chating/room.jsp

채팅방리스트 db 연결

---

src/main/java/com/example/controller/CommunityController.java
src/main/java/com/example/dao/CommunityRepository.java
src/main/java/com/example/domain/ImgFileVO.java
src/main/java/com/example/service/community/CommunityService.java
src/main/java/com/example/service/community/CommunityServiceImpl.java
src/main/webapp/WEB-INF/views/include/community/writeDaily.jsp
src/main/webapp/WEB-INF/views/include/friend/friendProfile.jsp

Community 게시글 작성페이지

---

src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/domain/UserVO.java
src/main/java/com/example/service/signUpService/SignUpService.java
src/main/java/com/example/service/signUpService/SignUpServiceImpl.java
src/main/resources/static/signUpLogin/css/userStyle.css
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/include/signUp.jsp

signUp fixed but not completed

signUp fixed.. not completed

---

src/main/java/com/example/controller/AgencyController.java
src/main/webapp/WEB-INF/views/include/agencyDetail.jsp
src/main/webapp/WEB-INF/views/include/agencyHotelDetail.jsp
src/main/webapp/WEB-INF/views/include/agencyShelter.jsp
src/main/webapp/WEB-INF/views/include/agencyShelterDetail.jsp
src/main/webapp/WEB-INF/views/index.jsp

agencyhotel및 보호소 페이지

---

src/main/java/com/example/controller/HomeController.java
src/main/webapp/WEB-INF/views/include/footer-style-3.jsp
src/main/webapp/WEB-INF/views/index.jsp

footer 수리 중

---

src/main/resources/static/css/chating/chatingFriend.css
src/main/webapp/WEB-INF/views/chating/chat.jsp

채팅방화면 채팅방이름 조금수정

---

src/main/java/com/example/controller/HomeController.java
src/main/webapp/WEB-INF/views/include/Header.jsp
src/main/webapp/WEB-INF/views/index.jsp

헤더 수정 및 메인컨트롤러 주석

---

src/main/java/com/example/controller/HomeController.java

메인페이지 들어갈수있게 수정

---

src/main/java/com/example/controller/AgencyController.java
src/main/java/com/example/dao/AbandonedRepository.java
src/main/java/com/example/domain/AbandonedVO.java
src/main/java/com/example/service/agency/AgencyService.java
src/main/java/com/example/service/agency/AgencyServiceImpl.java
src/main/webapp/WEB-INF/views/include/agencyShelter.jsp

paging 애견 보호소 페이지

---

src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/service/signUpService/SignUpService.java
src/main/java/com/example/service/signUpService/SignUpServiceImpl.java
src/main/resources/static/signUpLogin/css/userStyle.css
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/include/Header.jsp
src/main/webapp/WEB-INF/views/include/Login.jsp
src/main/webapp/WEB-INF/views/include/signUp.jsp

회원가입 작업 시작

---

src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/service/signUpService/SignUpService.java
src/main/java/com/example/service/signUpService/SignUpServiceImpl.java
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/include/Header.jsp
src/main/webapp/WEB-INF/views/include/Login.jsp
src/main/webapp/WEB-INF/views/include/signUp.jsp

유효성검사 테스트중

---

src/main/java/com/example/controller/admin/AdminMainController.java
src/main/java/com/example/dao/AgencyRepository.java
src/main/java/com/example/domain/AgencyVO.java
src/main/java/com/example/service/admin/AdminAgencyService.java
src/main/java/com/example/service/admin/AdminAgencyServiceImpl.java
src/main/webapp/WEB-INF/views/admin/facilities/adminHotel.jsp
src/main/webapp/WEB-INF/views/admin/facilities/paging.jsp

애견호텔 페이징 처리(추후에 시설별로 페이징 처리하는거로 수정 예정)
- agency VO, service 수정
- 어드민 컨트롤러 수정
- paging.jap파일 추가
- adminHotel.jsp 수정

관리자 페이지 수정

---

src/main/java/com/example/controller/ChatingController.java
src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/controller/api/ApiController.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/domain/UserVO.java
src/main/java/com/example/service/signUpService/SignUpService.java
src/main/java/com/example/service/signUpService/SignUpServiceImpl.java
src/main/resources/static/signUpLogin/css/userStyle.css
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/include/Login.jsp
src/main/webapp/WEB-INF/views/include/signUp.jsp

유효성 검사 및 UserVO 변경

---

src/main/java/com/example/controller/HomeController.java
src/main/webapp/WEB-INF/views/include/Header.jsp

Header 버튼 제거

---

src/main/java/com/example/controller/HomeController.java
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/include/signUp.jsp

회원가입&기능 구현 80%

---

src/main/resources/static/signUpLogin/css/userStyle.css
src/main/webapp/WEB-INF/views/include/Login.jsp
src/main/webapp/WEB-INF/views/include/signUp.jsp

버튼 오타 수정 및 크기조절

---

src/main/java/com/example/controller/ChatingController.java
src/main/java/com/example/handler/SocketHandler.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java

controller 랑 service 기능 부분수정

---

src/main/java/com/example/controller/ChatingController.java
src/main/java/com/example/dao/ChatingRoomRepository.java
src/main/java/com/example/domain/UserVO.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/webapp/WEB-INF/views/chating/room.jsp

채팅방리스트 페이징기능

---

src/main/java/com/example/controller/api/ApiController.java
src/main/java/com/example/dao/ChatingRoomRepository.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/webapp/WEB-INF/views/chating/room.jsp

채팅방리스트 검색기능

---

src/main/java/com/example/controller/AgencyController.java
src/main/java/com/example/service/agency/AgencyService.java
src/main/java/com/example/service/agency/AgencyServiceImpl.java
src/main/webapp/WEB-INF/views/include/agencyCafe.jsp
src/main/webapp/WEB-INF/views/include/agencyCafeDetail.jsp
src/main/webapp/WEB-INF/views/include/agencyShelterDetail.jsp
src/main/webapp/WEB-INF/views/include/encyclopedia.jsp
src/main/webapp/WEB-INF/views/index.jsp

agency 카페 및 카페 상세보기 완성 및 백과사전페이지 수정중

agency 카페 및 카페 상세보기 완성 및 백과사전페이지 수정중

---

src/main/webapp/WEB-INF/views/chating/room.jsp

채팅방 검색기능수정

---

src/main/java/com/example/dao/ChatingRoomRepository.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/webapp/WEB-INF/views/chating/chat.jsp

채팅방 user 사진 맞추기

---

src/main/java/com/example/controller/ChatingController.java
src/main/webapp/WEB-INF/views/chating/chat.jsp
src/main/webapp/WEB-INF/views/chating/friend.jsp
src/main/webapp/WEB-INF/views/chating/friendChat.jsp

session test

---

src/main/java/com/example/controller/ChatingController.java
src/main/java/com/example/dao/FriendRepository.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/resources/static/css/chating/chatingFriend.css
src/main/webapp/WEB-INF/views/chating/chat.jsp
src/main/webapp/WEB-INF/views/chating/friendChat.jsp

1:1채팅 친구목록

---

src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/UserRepository.java
src/main/resources/static/signUpLogin/css/userStyle.css
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/include/signUp.jsp

회원가입 중복찾기 에러 수정 (vo 변경으로 인한 이메일 값 null)

회원가입 중복찾기 에러 수정

---

src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/domain/UserVO.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/include/Header.jsp
src/main/webapp/WEB-INF/views/include/Login.jsp
src/main/webapp/WEB-INF/views/include/signUp.jsp
src/main/webapp/WEB-INF/views/index.jsp

로그인 세션 확인완료

---

src/main/java/com/example/service/agency/AgencyServiceImpl.java
src/main/resources/static/agency/js/kakaoMap.js
src/main/webapp/WEB-INF/views/include/agencyCafe.jsp
src/main/webapp/WEB-INF/views/include/agencyHotel.jsp

Agency agencyCafe 카카오맵 수정중

---

src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/java/com/example/service/signUpService/SignUpServiceImpl.java
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/include/Header.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageProfile.jsp

로그아웃 기능구현 + 회원탈퇴 구현 중
Header에 구현화면 태그 걸었음

로그아웃 및 회원탈퇴 기능구현

---

src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java

마이프로필 수정작업 중

---

src/main/java/com/example/dao/FriendRepository.java
src/main/java/com/example/dao/ImgRepository.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/webapp/WEB-INF/views/chating/friend.jsp
src/main/webapp/WEB-INF/views/chating/friendChat.jsp

1:1채팅 친구클릭 websocket 재연결

---

src/main/java/com/example/domain/CommentVO.java
src/main/java/com/example/domain/ImgVO.java
src/main/java/com/example/domain/ReportVO.java

vo 클래스 변수이름수정

---

src/main/java/com/example/controller/ChatingController.java
src/main/java/com/example/controller/api/ApiController.java
src/main/java/com/example/domain/FriendChatingVO.java
src/main/java/com/example/handler/SocketHandler.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/resources/static/css/chating/chatingFriend.css
src/main/webapp/WEB-INF/views/chating/friendChat.jsp
src/main/webapp/WEB-INF/views/include/Header.jsp

1:1 친구채팅 db에 저장

---

src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/java/com/example/service/signUpService/SignUpServiceImpl.java
src/main/webapp/WEB-INF/views/include/myPage/myPageProfile.jsp
src/main/webapp/WEB-INF/views/include/signUp.jsp

필요없는 코드 제거 및 정리

---

src/main/java/com/example/controller/AgencyController.java
src/main/java/com/example/controller/api/ApiController.java
src/main/java/com/example/dao/AgencyRepository.java
src/main/java/com/example/dao/DogKindRepository.java
src/main/java/com/example/service/agency/AgencyService.java
src/main/java/com/example/service/agency/AgencyServiceImpl.java
src/main/webapp/WEB-INF/views/include/agencyCafe.jsp
src/main/webapp/WEB-INF/views/include/agencyHotel.jsp
src/main/webapp/WEB-INF/views/include/agencytestDetail.jsp
src/main/webapp/WEB-INF/views/include/encyclopedia.jsp
src/main/webapp/WEB-INF/views/include/encyclopediaDetail.jsp

agency 호텔 검색기능 추가 및 신고 모달창 크기 수정 및 백과사전 상세페이지 구현

agency 호텔 검색기능 추가 및 신고 모달창 크기 수정 및 백과사전 상세페이지 구현

---

src/main/java/com/example/walk/WalkVO.java
src/main/webapp/WEB-INF/views/walk/walk.jsp

산책로 거리계산 및 오늘날짜 컬럼추가

---

src/main/java/com/example/handler/SocketHandler.java
src/main/webapp/WEB-INF/views/chating/friendChat.jsp
src/main/webapp/WEB-INF/views/chating/room.jsp

websocket 서버 수정

---

src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/PetRepository.java
src/main/java/com/example/domain/PetVO.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/webapp/WEB-INF/views/include/myPage/imgModify.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogAdd.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageProfile.jsp

프로필사진 출력 & 마이페이지 - 반려동물 페이지 작업

---

src/main/java/com/example/controller/api/ApiController.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/webapp/WEB-INF/views/chating/friendChat.jsp

장의침 퐈이팅 및 기능 수정

---

src/main/java/com/example/domain/PetVO.java
src/main/webapp/WEB-INF/views/include/myPage/myPageDogAdd.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogDetail.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogList.jsp

vo Integer 변경 / 반려견정보 수정 중

---

src/main/java/com/example/controller/AgencyController.java
src/main/java/com/example/controller/admin/AdminMainController.java
src/main/java/com/example/dao/ReviewRepository.java
src/main/java/com/example/service/agency/AgencyService.java
src/main/java/com/example/service/agency/AgencyServiceImpl.java
src/main/webapp/WEB-INF/views/include/agencyCafe.jsp
src/main/webapp/WEB-INF/views/include/agencyCafeDetail.jsp
src/main/webapp/WEB-INF/views/include/agencyHotel.jsp
src/main/webapp/WEB-INF/views/include/agencyHotelDetail.jsp

agency 호텔 및 카페 리뷰테이블 DB 보여주기 / insert 리뷰 작성

agency 호텔 및 카페 리뷰테이블 DB 보여주기 / insert 리뷰 작성

---

src/main/webapp/WEB-INF/views/include/friend/friendFind.jsp

친구목록 sidebar 수정 중

---

src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/java/com/example/service/signUpService/SignUpService.java
src/main/java/com/example/service/signUpService/SignUpServiceImpl.java
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/include/Login.jsp
src/main/webapp/WEB-INF/views/include/changePassPage.jsp
src/main/webapp/WEB-INF/views/include/findPassPage.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogAdd.jsp

비밀번호 찾기/변경 작업 중

---

src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java

반려견추가 기능 구현 중

---

src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/resources/static/signUpLogin/css/petStyle.css
src/main/webapp/WEB-INF/views/include/Header.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageBoard.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogAdd.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogDetail.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogList.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageProfile.jsp

경로수정 및 반려견추가작업중

---

src/main/java/com/example/controller/LoginController.java
src/main/webapp/WEB-INF/views/include/Header.jsp

header 살짝 수정

---

src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/webapp/WEB-INF/views/friend/friendList.jsp
src/main/webapp/WEB-INF/views/friend/friendProfile.jsp
src/main/webapp/WEB-INF/views/include/Footer.jsp
src/main/webapp/WEB-INF/views/include/Header.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogAdd.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogDetail.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogList.jsp

자잘한 사이드바 경로수정

---

src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/webapp/WEB-INF/views/admin/common/adminFooter.jsp
src/main/webapp/WEB-INF/views/include/Footer.jsp
src/main/webapp/WEB-INF/views/include/Login.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogDetail.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogList.jsp

반려견상세보기(이미지제외)

---

src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/domain/PetVO.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/webapp/WEB-INF/views/include/Footer.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogAdd.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogList.jsp

반려견 추가 수정 중..

---

src/main/java/com/example/controller/ChatingController.java
src/main/java/com/example/controller/api/ApiController.java
src/main/java/com/example/domain/FriendChatingVO.java
src/main/java/com/example/domain/UserVO.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/resources/static/js/chating/friendChat.js

1:1채팅페이지 떠나는시간 저장

---

src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/domain/ImgVO.java
src/main/webapp/WEB-INF/views/friend/friendFind.jsp
src/main/webapp/WEB-INF/views/include/Header.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageProfile.jsp

헤더, friendFind aside 수정중 + 반려견추가

헤더, friendFind aside 수정중

---

src/main/java/com/example/controller/FriendController.java
src/main/java/com/example/dao/PetRepository.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/webapp/WEB-INF/views/friend/friendList.jsp
src/main/webapp/WEB-INF/views/include/Header.jsp

친구List 페이징랑 해당내용 뜨기

---

src/main/java/com/example/community/CommunityRepository.java
src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/CommentRepository.java
src/main/java/com/example/dao/ImgRepository.java
src/main/java/com/example/dao/LikeItRepository.java
src/main/java/com/example/dao/PetRepository.java
src/main/java/com/example/dao/ReviewRepository.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/webapp/WEB-INF/views/include/myPage/myPageBoard.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogDetail.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogList.jsp

마이페이지 -리스트 완료 / 반려견추가 완료

---

src/main/webapp/WEB-INF/views/agency/agencyHospital.jsp
src/main/webapp/WEB-INF/views/agency/agencyHotelDetail.jsp
src/main/webapp/WEB-INF/views/agency/agencyShelterSignup.jsp
src/main/webapp/WEB-INF/views/agency/encyclopedia.jsp

입양페이지에서 로그인시 입양신청 버튼 보이기 및 정보기관리스트 크기칸 맞춤

입양페이지에서 로그인시 입양신청 버튼 보이기 및 정보기관리스트 크기칸 맞춤

---

src/main/resources/static/main/weather.js
src/main/webapp/WEB-INF/views/include/Header.jsp

헤더 날씨지도 아이디 수정

---

pom.xml
src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/domain/UserVO.java
src/main/java/com/example/mail/MailDto.java
src/main/java/com/example/mail/SendEmailService.java
src/main/java/com/example/service/signUpService/SignUpService.java
src/main/java/com/example/service/signUpService/SignUpServiceImpl.java
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/include/findPassPage.jsp

이메일로 인증번호 전송

---

src/main/webapp/WEB-INF/views/agency/agencyCafe.jsp
src/main/webapp/WEB-INF/views/agency/agencyCafeDetail.jsp
src/main/webapp/WEB-INF/views/agency/agencyHall.jsp
src/main/webapp/WEB-INF/views/agency/agencyHallDetail.jsp
src/main/webapp/WEB-INF/views/agency/agencyHospital.jsp
src/main/webapp/WEB-INF/views/agency/agencyHospitalDetail.jsp
src/main/webapp/WEB-INF/views/agency/agencyHotel.jsp
src/main/webapp/WEB-INF/views/agency/agencyHotelDetail.jsp

agency 지도 띄우기 및 상세보기 지도 위치

---

src/main/java/com/example/controller/FriendController.java
src/main/java/com/example/dao/UserRepository.java

친구찾기 jpql수정

---

src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/dao/ImgRepository.java
src/main/java/com/example/dao/PetRepository.java
src/main/java/com/example/domain/PetVO.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/webapp/WEB-INF/views/include/myPage/myPageDogDetail.jsp
src/main/webapp/WEB-INF/views/include/myPage/myPageDogList.jsp

마이페이지 - 반려견리스트 페이징

---

src/main/java/com/example/controller/api/ApiController.java
src/main/java/com/example/dao/UserRepository.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/webapp/WEB-INF/views/friend/friendFind.jsp

친구찾기페이지 요청발송

---

src/main/java/com/example/controller/AgencyController.java
src/main/java/com/example/dao/ReviewRepository.java
src/main/java/com/example/domain/AgencyVO.java
src/main/java/com/example/service/agency/AgencyService.java
src/main/java/com/example/service/agency/AgencyServiceImpl.java
src/main/webapp/WEB-INF/views/agency/agencyCafe.jsp
src/main/webapp/WEB-INF/views/agency/agencyHotel.jsp
src/main/webapp/WEB-INF/views/agency/agencyHotelDetail.jsp

agency 호텔 별점 평균 구하기 및 평균값 별점 채우는중

agency 호텔 별점 평균 구하기 및 평균값 별점 채우는중

---

src/main/webapp/WEB-INF/views/include/Header.jsp

메인페이지 알림뜨기

---

src/main/java/com/example/controller/HomeController.java
src/main/java/com/example/dao/LikeItRepository.java
src/main/java/com/example/service/chatingService/ChatingService.java
src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/webapp/WEB-INF/views/include/Main.jsp

메인 페이지 인기순

---

src/main/java/com/example/service/chatingService/ChatingServiceImpl.java
src/main/webapp/WEB-INF/views/include/Main.jsp

메인페이지 user 사진 뜨기

---

src/main/java/com/example/controller/LoginController.java
src/main/java/com/example/service/loginService/LoginService.java
src/main/java/com/example/service/loginService/LoginServiceImpl.java
src/main/resources/static/signUpLogin/js/member.js
src/main/webapp/WEB-INF/views/myPage/myPageProfile.jsp
src/main/webapp/WEB-INF/views/myPage/pwChangePage.jsp
src/main/webapp/WEB-INF/views/myPage/pwCheckPage.jsp
src/main/webapp/WEB-INF/views/walk/myPage/changePassPage.jsp

비밀번호 수정ㅇ완료

---

src/main/java/com/example/service/agency/AgencyServiceImpl.java
src/main/webapp/WEB-INF/views/agency/agencyCafe.jsp
src/main/webapp/WEB-INF/views/agency/agencyHall.jsp
src/main/webapp/WEB-INF/views/agency/agencyHospital.jsp
src/main/webapp/WEB-INF/views/agency/agencyHotel.jsp
src/main/webapp/WEB-INF/views/agency/agencyHotelDetail.jsp

agency 별점 평점 나타내기
